{"uid":"78d329bee426f3c","name":"test_print15","fullName":"apiauto.test_doit5#test_print15","historyId":"004f2fb62e99c49c3bb45e229dfbc5b0","time":{"start":1685195446594,"stop":1685195446598,"duration":4},"status":"failed","statusMessage":"AssertionError: assert '1 function' in '2 function call'","statusTrace":"def test_print15():\n        flag = '2 function call'\n        printknow1()\n        printknow3()\n>       assert '1 function' in flag\nE       AssertionError: assert '1 function' in '2 function call'\n\napiauto\\test_doit5.py:30: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"parentSuite","value":"apiauto"},{"name":"suite","value":"test_doit5"},{"name":"host","value":"zhangtaopc"},{"name":"thread","value":"11624-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"apiauto.test_doit5"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"78d329bee426f3c.json","parameterValues":[]}