{"name": "test_print13", "status": "failed", "statusDetails": {"message": "AssertionError: assert 14 == 15", "trace": "def test_print13():\n        num = 14\n        logging.info('i am writing logs...')\n        logger.info('i am writing logs 2...')\n        printknow2()\n>       assert num == 15\nE       assert 14 == 15\n\napiauto\\test_doit5.py:18: AssertionError"}, "attachments": [{"name": "log", "source": "c5cc122a-7464-483d-b8ca-6ec2bff799a0-attachment.txt", "type": "text/plain"}], "start": 1685195446533, "stop": 1685195446539, "uuid": "6fc8e959-6e1b-44ff-9b93-62441b2d0a2d", "historyId": "5c84f781d22b7be0851bd3e9e748571e", "testCaseId": "3da96bdadbc715439175681859fa033d", "fullName": "apiauto.test_doit5#test_print13", "labels": [{"name": "parentSuite", "value": "apiauto"}, {"name": "suite", "value": "test_doit5"}, {"name": "host", "value": "zhangtaopc"}, {"name": "thread", "value": "11624-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "apiauto.test_doit5"}]}